// File generated by FlutterFire CLI for STAGING (placeholder version).
// Replace placeholders by running:
// flutterfire configure --project <staging-project-id> \
//   --out lib/firebase_options_staging.dart \
//   --platforms=android,ios,macos,web,windows
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class StagingFirebaseOptions {
  static const String _placeholder = 'REPLACE_WITH_STAGING_VALUE';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'StagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static void assertConfigured() {
    if (!_isConfigured) {
      throw StateError(
        'Staging FirebaseOptions are placeholders. Run flutterfire configure '
        'with --out lib/firebase_options_staging.dart and commit the result.',
      );
    }
  }

  static bool get _isConfigured =>
      _isValid(android) &&
      _isValid(ios) &&
      _isValid(macos) &&
      _isValid(web) &&
      _isValid(windows);

  static bool _isValid(FirebaseOptions options) {
    return !_isPlaceholder(options.apiKey) &&
        !_isPlaceholder(options.appId) &&
        !_isPlaceholder(options.projectId) &&
        !_isPlaceholder(options.messagingSenderId);
  }

  static bool _isPlaceholder(String value) {
    return value.isEmpty || value == _placeholder;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    authDomain: _placeholder,
    storageBucket: _placeholder,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    storageBucket: _placeholder,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    storageBucket: _placeholder,
    iosClientId: _placeholder,
    iosBundleId: _placeholder,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    storageBucket: _placeholder,
    iosClientId: _placeholder,
    iosBundleId: _placeholder,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    authDomain: _placeholder,
    storageBucket: _placeholder,
  );

  // Linux is local-only (no auth). Keep placeholder config to avoid usage.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    authDomain: _placeholder,
    storageBucket: _placeholder,
  );
}
