// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPx5HN9jcgWaHtQZ1XjgUcQ8fQLWqcxQ',
    appId: '1:32274647226:web:a28a9407367c8f24159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    authDomain: 'focus-interval.firebaseapp.com',
    storageBucket: 'focus-interval.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARsxaYow2OsXu_KNb7DGmAQ7vVWYF4R8',
    appId: '1:32274647226:android:7405613b584e2a09159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    storageBucket: 'focus-interval.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZcDExyzY-ef3XGQ1Vn7MvGUj8P5IB5Y',
    appId: '1:32274647226:ios:6feb760358bfba46159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    storageBucket: 'focus-interval.firebasestorage.app',
    iosClientId: '32274647226-2496tlb97lrbt0qim7qu7s0off27ttnp.apps.googleusercontent.com',
    iosBundleId: 'com.marcdevelopez.focusinterval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZcDExyzY-ef3XGQ1Vn7MvGUj8P5IB5Y',
    appId: '1:32274647226:ios:6feb760358bfba46159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    storageBucket: 'focus-interval.firebasestorage.app',
    iosClientId: '32274647226-2496tlb97lrbt0qim7qu7s0off27ttnp.apps.googleusercontent.com',
    iosBundleId: 'com.marcdevelopez.focusinterval',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASPx5HN9jcgWaHtQZ1XjgUcQ8fQLWqcxQ',
    appId: '1:32274647226:web:fa0c033943ccf69c159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    authDomain: 'focus-interval.firebaseapp.com',
    storageBucket: 'focus-interval.firebasestorage.app',
  );

  // Linux usa la misma configuración web (appId web) que Windows.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyASPx5HN9jcgWaHtQZ1XjgUcQ8fQLWqcxQ',
    appId: '1:32274647226:web:fa0c033943ccf69c159a83',
    messagingSenderId: '32274647226',
    projectId: 'focus-interval',
    authDomain: 'focus-interval.firebaseapp.com',
    storageBucket: 'focus-interval.firebasestorage.app',
  );

}
